version: '3'

services:
  keycloak:
    image: jboss/keycloak:11.0.1
    environment:
      DB_VENDOR: postgres
      DB_ADDR: 192.168.1.11
      DB_PORT: 32558
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
      KEYCLOAK_LOGLEVEL: DEBUG
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=500,initialize_sql="CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
    command: ["/opt/jboss/bin/jboss-cli.sh --file=/opt/jboss/bin/migrate-standalone.cli"]
    # command: /opt/jboss/bin/jboss-cli.sh --file=/opt/jboss/bin/migrate-standalone.cli
